# Generated by Django 5.0.3 on 2024-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='med_kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medname', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='medkit',
        ),
    ]
